#name: main
#on: [push]
#jobs:
  #check-python-version:
   # runs-on: ubuntu-latest
    #steps:
     # - uses: actions/checkout@v3
      #- uses: actions/setup-python@v3
       # with:
        #  python-version: '3.9'
      #- run: python --version
      #- name: python script
       # run: python python.py
name: main
## Triggers the workflow on when there is a push, or
## pull request on the main branch
on: push
env:
 ## Environment variable
  name: "vikram"
jobs:
  job1:
    ## The type of runner that the job will run on
    runs-on: self-hosted
   # env:
 ## Environment variable
      #  name: "vikram"
    steps:
        - name: step 1
          ## Reference your environment variables
          # run: echo "The API key is:${{env.API_KEY}}"  
          run: echo "The name is:$name"  
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
## Another way reference your environment variables
        run: echo "The name is:$name"         
